icons = "awesome"

[theme]
name = "modern"

[theme.overrides]
idle_bg = "#373d48"
separator = "\uE0C2"

[[block]]
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "sound"

[[block]]
block = "music"
#player = "spotify"
buttons = ["play", "next"]

[[block]]
block = "time"
interval = 60
format = "%d/%m/%Y %R"
timezone = "Europe/Paris"
